# Generated by Django 4.1.3 on 2023-05-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='Profilepicture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='Subjectstaught',
            field=models.TextField(max_length=1000),
        ),
    ]
