# Generated by Django 4.1.3 on 2023-05-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0002_alter_teachermodel_profilepicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='Profilepicture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
