# Generated by Django 4.1.3 on 2023-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0004_alter_teachermodel_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='Profilepicture',
            field=models.FileField(upload_to='profilepic'),
        ),
    ]
