# Generated by Django 4.1.3 on 2023-05-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0005_alter_teachermodel_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='Profilepicture',
            field=models.ImageField(upload_to='profilepic/'),
        ),
    ]
